[package]
name = "rustpi"
version = "0.1.0"
edition = "2018"
authors = ["tonnylyz <lyztonny@gmail.com>"]

[dependencies]
rlibc = "1.0.0"
register = "1.0.2"
buddy_system_allocator = "0.7.0"
spin = "0.9.0"
xmas-elf = "0.7.0"
elfloader = "0.11.0"
cfg-if = "1.0.0"
log = "0.4"

addr2line = { git = "https://github.com/tonnylyz/addr2line", default-features = false, features = ["alloc", "rustc-demangle"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { git = "https://github.com/tonnylyz/cortex-a" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/tonnylyz/riscv" }

[features]
default = []
aarch64_virt = []
riscv64_virt = []
user_release = []

[profile.release]
debug = true
