[package]
name = "rustpi"
version = "0.1.0"
edition = "2021"
authors = ["tonnylyz <lyztonny@gmail.com>"]

[dependencies]
# to be phased out
rlibc = "1.0.0"

# fundamental
cfg-if = "1.0.0"
log = "0.4.14"
static_assertions = "1.1.0"
#fallible_collections = "0.4.3"

buddy_system_allocator = "0.8.0"
spin = "0.9.2"
xmas-elf = "0.8.0"

common = { path = "common" }
unwind = { path = "lib/unwind" }
inject = { path = "inject" }

[dependencies.tock-registers]
version = "0.7.0"
default-features = false
features = ["register_types"]

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { git = "https://github.com/tonnylyz/cortex-a" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/tonnylyz/riscv" }
#k210-pac = { path = "../k210-pac", default-features = false, features = [], optional = true  }
k210-hal = { path = "../k210-hal" }

[features]
default = ["user_release"]
user_release = []
guest = []
k210 = []

[profile.release]
debug = true
