[package]
name = "rustpi"
version = "0.1.0"
edition = "2018"
authors = ["tonnylyz <lyztonny@gmail.com>"]
build = "build.rs"

[dependencies]
rlibc = "0.1"
register = "1.0.2"
buddy_system_allocator = "0.6.0"
spin = "0.5.2"
xmas-elf = "0.7.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

elfloader = "0.11.0"
backtracer = { path="../backtracer" }
addr2line = { path="../addr2line", default-features = false, features = ["alloc", "rustc-demangle"] }
#addr2line =  { version = "0.14.1", default-features = false, features = ["alloc", "rustc-demangle"] }
[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { path = "../cortex-a" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/tonnylyz/riscv" }

[features]
default = []
aarch64_virt = []
riscv64_virt = []
