[package]
name = "rustpi"
version = "0.1.0"
edition = "2018"
authors = ["tonnylyz <lyztonny@gmail.com>"]
build = "build.rs"

[dependencies]
rlibc = "1.0.0"
register = "1.0.2"
buddy_system_allocator = "0.7.0"
spin = "0.9.0"
xmas-elf = "0.7.0"
fatfs = { version = "0.3.5", features = ["core_io", "alloc"], default-features = false }
core_io = "0.1"

elfloader = "0.11.0"
backtracer = { path = "../backtracer" }
addr2line = { path = "../addr2line", default-features = false, features = ["alloc", "rustc-demangle"] }
#addr2line =  { version = "0.14.1", default-features = false, features = ["alloc", "rustc-demangle"] }
[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = { path = "../cortex-a" }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/tonnylyz/riscv" }

# ide only
#[target.'cfg(target_arch = "x86_64")'.dependencies]
#fatfs = { version = "0.3.5" }


[features]
default = []
aarch64_virt = []
riscv64_virt = []
