[package]
name = "trusted"
version = "0.1.0"
edition = "2018"
authors = ["tonnylyz <lyztonny@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
spin = "0.9.0"
register = "1.0.2"
libtrusted = { path = "../lib/libtrusted" }
microcall = { path = "../lib/microcall" }
common = { path = "../common" }