[package]
name = "rustpi-user"
version = "0.1.0"
edition = "2018"
authors = ["tonnylyz <lyztonny@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
register = "1.0.2"
buddy_system_allocator = "0.7.0"
spin = "0.9.0"
bitflags = "1.1.0"